# -*- mode: ruby -*-
# vi: set ft=ruby :

# Define variables, with default values, that are read from OS env vars
host_name = ENV["VAGRANT_HOST_NAME"]  || "skel-ubuntu-1904"
host_cpu  = ENV["VAGRANT_HOST_CPU"]   || "2"
host_ram  = ENV["VAGRANT_HOST_RAM"]   || "2048"
host_ip   = ENV["VAGRANT_HOST_IP"]    || "192.168.45.30"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/disco64"
  config.vm.hostname = host_name
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: host_ip, :mac => "5C4509297620"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #

    vb.name = host_name
    # Customize the amount of memory on the VM:
    vb.cpus = host_cpu
    vb.memory = host_ram

  # Fix for slow Ubuntu 19.04 boot time
  # The VM serial port apparently needs to be attached to a file
  # https://bugs.launchpad.net/cloud-images/+bug/1829625
     vb.customize [ "modifyvm", :id, "--uartmode1", "file",
                   File.join(Dir.pwd, "ubuntu-disco-19.04-cloudimg-console.log")
     ]
   end

  #
  # View the documentation for the provider you are using for more
  # information on available options.

   config.vm.provision "file",
    source: "../../../movein",
    destination: "~/movein"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
        echo -e "~~~~~~ Performing movein provisioning ~~~~~~"
        export BASE_GROUPS=sudo
        mv /home/vagrant/movein /root
        cd /root/movein
        ./movein.sh base_user ubuntu_base ubuntu_dev base_dev
  SHELL

end
